conf.py:
  project: Formhandler ClearLog Task
  version: 0.1.0
  release: 0.1.0
  latex_documents:
  - - Index
    - formhandler_clearlog_task.tex
    - Formhandler ClearLog Task
    - Dan Untenzu
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
